### ISSUE TITLE
Use builder pattern for Account transactions

### ISSUE THREAD

**Issue by xJonathanLEI** [xJonathanLEI/starknet-rs#101]
Follow up issue on #98. Instead of hard-coding a fee estimation process, we should adapt the builder pattern to allow users to specify transaction fees.

Such a pattern should also be applied to nonce fetching. Currently `execute()` forces callers to supply a nonce, meaning it's the caller's responsibility to call `get_nonce()` before calling `execute()`. It makes the `Account` trait hard to use.

**Comment by xJonathanLEI** [comment]
What I have in mind is the following.

We should change the `execute()` method in `Account` trait to:

- not accept a `nonce` parameter; and
- return some new type `AccountCall` (as always, naming not final), which contains some `send()` method that will actually make the requests.

The proposed new type `AccountCall` will have these methods, apart from `send()`:

- `nonce()`
- `max_fee()`

When `send()` is called, it'll use whatever `nonce` and `max_fee` supplied. If none is given, it will call `get_nonce()` and `estimate_fees` to figure out automatically.

@milancermak WDYT?

**Comment by milancermak** [comment]
Yes, this sounds great!

What do you think about having to use explicit and mutually exclusive setters for nonce / fee? So you'd either have to `nonce(20)` to set it as you wish or `use_next_nonce()` to get it from the `get_nonce()` call. I guess the only advantage is that the values are set explicitly instead of using a default. I have no strong feelings about this, just curious what your opinion is.

**Comment by xJonathanLEI** [comment]
Hmm I think one of the benefits of using this pattern is that we can hide away the complicated details (nonce & fees) from users. So I'd vote for not having to explicitly set `use_next_nonce()`.
