### ISSUE TITLE
Any plans to export `starknet_crypto` in `starknet`?

### ISSUE THREAD

**Issue by Pet3ris** [xJonathanLEI/starknet-rs#242]
Using `get_public_key` in a project and curious if there is another way than importing the 2 crates separately? I understand some of the crypto functions are re-exported as part of core but this one didn't seem to be included.

cc @fracek

**Comment by xJonathanLEI** [comment]
Hmmm TBH I'm not entirely sure about this one. The rationale behind _not_ exposing `starknet-crypto` is that, as explained in the subcrate's README, it's very easy to shoot yourself in the foot when using `ecdsa_sign` incorrectly (I'm not a cryptographer but I'm pretty certain it's the only one with risks due to the `k` scalar), and users are encouraged to use high-level abstractions.

I actually based most of the library design on [`ethers-rs`](https://github.com/gakonst/ethers-rs), and AFAIK there's also no way to convert a `U256` private key directly to a `U256` public key or an `Address`. You have to use the `SigningKey` type for that, or just import the upstream crypto crate (same as importing `starknet-crypto` here). I might be wrong but IIRC there's also no way to do that in `ethers.js` without using a `Wallet` type (aka. high level abstraction) or something?

Btw the equivalent of `ethers-rs`'s `SigningKey` is `starknet_signers::SigningKey`. You can get the same result as `get_public_key` with:

```rust
let public_key = SigningKey::from_secret_scalar(private_key).verifying_key().scalar();
```

**Comment by Pet3ris** [comment]
Thanks @xJonathanLEI - that makes sense to me and thanks for pointing out the alternative. Will refactor accordingly! I was translating from Python code and I guess it didn't use the `ethers-rs` conventions.
