### ISSUE TITLE
Write tests and set up CI pipeline for running them

### ISSUE THREAD

**Issue by xJonathanLEI** [xJonathanLEI/starknet-rs#4]
There's currently zero test written for the project, making it hard to contribute without breaking stuff. We need to write tests and run them on `master` and PRs. After this is done, all new PRs that add/change Rust code must be accompanied with corresponding test cases.

TODOs:

- [x] add basic tests
- [x] set up CI for running tests
- [x] set up CI for `audit-check`, `cargo-udeps`, and `cargo-deny`

**Comment by milancermak** [comment]
I just started to work on a basic unit test suite 🤘I'll take this one then.

**Comment by milancermak** [comment]
@xJonathanLEI I've set up a simple [test action](https://github.com/xJonathanLEI/starknet-rs/actions/workflows/test.yaml) in 20f886bd - it runs `cargo test` for stable and nightly on the project. It's the first time I'm creating this for a Rust project so please let me know if I missed anything.

While researching how to do this, I've stumbled upon an [audit check](https://github.com/actions-rs/audit-check) action. Seems useful, should I set it up? And since I'm on the topic, what do you think about having [cargo udeps](https://github.com/est31/cargo-udeps) and [cargo deny](https://github.com/EmbarkStudios/cargo-deny)?

**Comment by xJonathanLEI** [comment]
@milancermak Nice one on the PR! I'm gonna check in a bit.

As for `cargo-udeps` and `cargo-deny`, I think it's a good idea to set those up as part of CI. But I'd probably skip the license check in `cargo-deny`, as we're not distributing bundled binaries anyways, and I'm not really familiar with license compatibility and stuff lol.

**Comment by milancermak** [comment]
Aye, good point on the license check in `cargo-deny`.

Will set up the rest tomorrow and open a PR.

**Comment by xJonathanLEI** [comment]
Closing as all items have been done.
