### ISSUE TITLE
estimateFee version support

### ISSUE THREAD

**Issue by apoorvsadana** [xJonathanLEI/starknet-rs#402]
Add support for `0x100000000000000000000000000000001` version in estimateFee rpc.

Currently, the testnet and mainnet support `0x100000000000000000000000000000001` version for the `estimateFee` rpc call. [Starknetjs](https://github.com/starkware-libs/cairo-lang/blob/00ee90123c0bbaffe13dd05a79d2d57b0cb747be/src/starkware/starknet/definitions/constants.py#LL64C9-L64C9) also uses this version by default when calling `estimateFee` within the `account.execute` method. 

However, `EstimateFeeRequest` struct in starknet-rs currently only supports versions 0x0 and 0x1 which causes calls made via starknetjs to break (it happened when we were trying to integrate a faucet to Madara and were using starknetjs for transfer calls).

**Comment by xJonathanLEI** [comment]
TBH personally I really don't like this feature, but at the same time we certainly _need_ this as otherwise projects using `starknet-rs` on the server side wouldn't be able to accept requests that make use of it.

So we just need to come up with a nice API that would make this work. There are a few options. For example we can turn all `BroadcastedXxxx` types into enums with variants `Normal` and `Query`, but that's too much breaking changes IMO.

What I feel comfortable with is to add a non-serialized *private* field `is_query: bool` to these types. The value is inferred from the `version` field when deserializing and affects `version` when serializing. This `is_query` field is then exposed through a *function* `fn is_query() -> bool`.

**Comment by xJonathanLEI** [comment]
Adding a private field also means you lose the ability to create new object though. So that's bad.

We need to either make this field public, or add a `fn new(xxx) -> Self` function.

**Comment by xJonathanLEI** [comment]
OK maybe we just make this a public field. These are low-level types so it's reasonable to expect users to be aware of exactly what each field does anyways. I do want to hide these complexities away from users but those whose would prefer a simpler interface might want to just use the high-level constructs.

**Comment by xJonathanLEI** [comment]
First draft of the query version support is now on the `dev/query_tx_version` branch.

**Comment by apoorvsadana** [comment]
Awesome! Thank you :)

**Comment by xJonathanLEI** [comment]
Forgot to link but this should have been resolved by #439.
