### ISSUE TITLE
How to fix private_key OutOfRange

### ISSUE THREAD

**Issue by whyubel1eve** [xJonathanLEI/starknet-rs#466]
Hi I 'm a beginner of starknet / starknet-rs. I need to use `get_public_key` from a private_key but there is a problem. My private_key was generated by randomBytes (32bytes) then to hex string. It's ok when using in starknet.js :
```javascript
  const starkPair = ec.getKeyPair(privateKey)
  const starkPub = ec.getStarkKey(starkPair)
``` 
but in starknet-rs: 
```rust
let private_key = FieldElement::from_hex_be(private).unwrap()
```
it threw an error of **OutOfRange**. Is there any way for me to use it normally?
I must use that private_key so that I can't change another one. Thanks.

**Comment by xJonathanLEI** [comment]
Technically Starknet.js is wrong here. When you randomly generate 32 bytes it's very likely the result is not a valid field element, as the Starknet field element is only 252 bits (it doesn't even make use of _all_ of 252 bits, meaning that even if you randomly generate just 252 bits (instead of 256) you could still get an invalid value). Starknet.js is incorrect in that it should have rejected your input. This is not a bug in `starknet-rs`. `starknet-rs` is correctly pointing out that your input is invalid.

That said, if you _do_ want to use that key, you would need to study the Starknet.js code to understand how it's turning your invalid input into a valid one (it _has to_ happen somewhere inside their code, after all). Then, you can use that valid, in-range, field element as private key in `starknet-rs`.

I haven't looked but my guess is that they simply take the your input and mod P. _If_ that's the case you can simply do that too and use the result for `starknet-rs`.

**Comment by roci10k** [comment]
thank u for reply, I will look into it.

**Comment by whyubel1eve** [comment]
thank u for reply, I will look into it.

**Comment by roci10k** [comment]
Hi @xJonathanLEI. I think I might need to give up that old private key. If I want to generate a valid private key that can be used in `starknet-rs`, what should I do?

**Comment by whyubel1eve** [comment]
Hi @xJonathanLEI. I think I might need to give up that old private key. If I want to generate a valid private key that can be used in starknet-rs, what should I do?

**Comment by xJonathanLEI** [comment]
Correct. Note that you don't need to directly import `starknet-signers`. It's re-exported through the umbrella `starknet` crate as well. So you can do something like `starknet::signers::xxxx`.
